sudo: false
language: php
php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install
  - npm install -g eslint@6

cache:
  directories:
    - $HOME/.composer/cache
    - .php_cs.cache

script:
- vendor/bin/phing ci
